title: German Utkin # your name (or website title) here
logo: "/images/logo1.png?raw=true"  # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Laboratory Assistant 
  <br>
  Lobachevsky University, ITMM
  <br><br>
  about: 
  <br>
  <a href="https://t.me/olithiumsunset">telegram</a> - for zoomers
  <a href="mailto:german.utkingu@gmail.com>gmail</a> - for boomers
#  <br>
#  <a href="https://vk.com/forodie">vk</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
